'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authClient } from '../../lib/auth';
import { addRecoveryActivityApi, closeRecoveryCaseApi, getRecoveryCaseApi, listAgingPoliciesApi, createAgingPolicyApi, listAgingQueueApi, listRecoveryQueueApi, listRecoverySuspensionsApi, reinstateSuspendedUserApi } from '../../lib/api';
import { apiFetch } from '../../lib/api';
import { BrandLogo } from '../../components/brand-logo';
import { inventoryStateLabel, roleLabel, statusLabel } from '../../lib/display';

type Me={authorization:{roles:string[];permissions:string[]}};
function bandClass(status:string){ return `chip ${status.toLowerCase()}`; }
function agingLabel(status:string){ return status === 'GREEN' ? 'On track' : status === 'ORANGE' ? 'Watch' : status === 'RED' ? 'Overdue' : status === 'PURPLE' ? 'Critical' : statusLabel(status); }
function activityLabel(value:string){ const labels:Record<string,string>={CONTACTED:'Contacted',VISITED:'Visit recorded',PROMISE_TO_RETURN:'Promise to return',FAILED_ATTEMPT:'Attempt unsuccessful',RECOVERED:'Recovered',ESCALATED:'Escalated'}; return labels[value]??statusLabel(value); }
function agingLabel(status:string){ return status === 'GREEN' ? 'On track' : status === 'ORANGE' ? 'Watch' : status === 'RED' ? 'Overdue' : status === 'PURPLE' ? 'Critical' : statusLabel(status); }
function activityLabel(value:string){ return statusLabel(value === 'CONTACTED' ? 'CONTACTED' : value === 'VISITED' ? 'VISITED' : value === 'PROMISE_TO_RETURN' ? 'PROMISE_TO_RETURN' : value === 'FAILED_ATTEMPT' ? 'FAILED_ATTEMPT' : value === 'RECOVERED' ? 'RECOVERED' : value === 'ESCALATED' ? 'ESCALATED' : value); }

export default function RecoveryPage(){
  const router=useRouter();
  const [aging,setAging]=useState<any[]>([]); const [cases,setCases]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [policies,setPolicies]=useState<any[]>([]); const [suspensions,setSuspensions]=useState<any[]>([]); const [me,setMe]=useState<Me|null>(null);
  const [policyForm,setPolicyForm]=useState({policyName:'Amaal Aging Policy',maximumDays:'18',warningDays:'8',criticalOverdueDays:'0',effectiveFrom:new Date(Date.now()+86400000).toISOString().slice(0,16),autoRecoveryEnabled:true});
  const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  async function load(){ try{ const session=await authClient.getSession(); if(!session?.data){router.replace('/login');return;} const [identity,a,c,p,s]=await Promise.all([apiFetch<Me>('/v1/me'),listAgingQueueApi(status?{status}: {}),listRecoveryQueueApi(),listAgingPoliciesApi(),listRecoverySuspensionsApi().catch(()=>({items:[]}))]); setMe(identity); setAging(a.items); setCases(c.items); setPolicies(p.items); setSuspensions(s.items); }catch(e){setError(e instanceof Error?e.message:'Unable to load recovery workspace.');} }
  useEffect(()=>{void load();},[status]);
  async function openCase(id:string){try{const r=await getRecoveryCaseApi(id);setSelected(r.item);}catch(e){setError(e instanceof Error?e.message:'Unable to load recovery case.');}}
  async function actionActivity(type:string){if(!selected)return;setBusy(true);setError('');try{await addRecoveryActivityApi(String(selected.id),{activityType:type,...(type==='RECOVERED'?{verifiedImei:String(selected.imei)}:{})});setMessage('Recovery activity recorded.');await load();await openCase(String(selected.id));}catch(e){setError(e instanceof Error?e.message:'We couldn’t record that activity. Please try again.');}finally{setBusy(false);}}
  async function createPolicy(){setBusy(true);setError('');try{await createAgingPolicyApi({policyName:policyForm.policyName,maximumDays:Number(policyForm.maximumDays),warningDays:Number(policyForm.warningDays),criticalOverdueDays:Number(policyForm.criticalOverdueDays),effectiveFrom:new Date(policyForm.effectiveFrom).toISOString(),autoRecoveryEnabled:policyForm.autoRecoveryEnabled});setMessage('Aging policy version created.');await load();}catch(e){setError(e instanceof Error?e.message:'We couldn’t save the aging rules. Please try again.');}finally{setBusy(false);}}
  async function reinstate(userId:string){const reason=window.prompt('Enter reinstatement reason');if(!reason)return;setBusy(true);setError('');try{await reinstateSuspendedUserApi(userId,reason);setMessage('User access reinstated.');await load();}catch(e){setError(e instanceof Error?e.message:'We couldn’t restore access. Please try again.');}finally{setBusy(false);}}
  async function closeCase(){if(!selected)return;const reason=window.prompt('Enter closure reason');if(!reason)return;setBusy(true);setError('');try{await closeRecoveryCaseApi(String(selected.id),reason);setMessage('Recovery case closed.');setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'We couldn’t close the recovery case. Please try again.');}finally{setBusy(false);}}
  return <main className="app-shell"><header className="topbar"><div className="topbar-brand"><BrandLogo variant="full" className="topbar-full-logo" priority/><div className="topbar-subtitle">Recovery</div></div><a className="ghost-button" href="/dashboard">Back to command center</a></header>
    <div className="workspace"><aside className="sidebar"><div className="section-label">OPERATIONS</div><nav><a className="nav-item" href="/dashboard">Command Center</a><a className="nav-item" href="/customers">Customers</a><a className="nav-item" href="/sales">Sales & Receipts</a><a className="nav-item" href="/inventory">Inventory & Devices</a><a className="nav-item" href="/finance">Finance</a><a className="nav-item active" href="/recovery">Recovery</a><a className="nav-item" href="/organization">People & Structure</a></nav><div className="section-label lower">INTELLIGENCE</div><a className="nav-item" href="/ai">Amaal AI</a></aside>
    <section className="content"><div className="content-header"><div><div className="eyebrow">AGING & RECOVERY</div><h1>Keep aged stock moving toward resolution.</h1><p className="muted">A device keeps its age even when it moves between people or locations.</p></div></div>
      {error?<div className="alert-card">{error}</div>:null}{message?<div className="card"><strong>{message}</strong></div>:null}
      <section className="card"><div className="section-head"><div><div className="card-label">AGING POLICY</div><h2>Company aging rules</h2></div></div><div className="table-wrap"><table><thead><tr><th>Policy</th><th>Maximum</th><th>Warning</th><th>Critical</th><th>Effective</th><th>Automatic follow-up</th></tr></thead><tbody>{policies.map((p:any)=><tr key={String(p.id)}><td>{p.policyName}</td><td>{p.maximumDays}d</td><td>{p.warningDays}d</td><td>{p.criticalOverdueDays}d</td><td>{new Date(p.effectiveFrom).toLocaleString()}</td><td>{p.autoRecoveryEnabled?'On':'Off'}</td></tr>)}{!policies.length?<tr><td colSpan={6} className="muted">No aging rules have been added yet.</td></tr>:null}</tbody></table></div>{me?.authorization.roles.includes('CEO')?<div className="scope-grid" style={{marginTop:16}}><input value={policyForm.policyName} onChange={e=>setPolicyForm({...policyForm,policyName:e.target.value})} placeholder="Policy name"/><input type="number" value={policyForm.maximumDays} onChange={e=>setPolicyForm({...policyForm,maximumDays:e.target.value})} placeholder="Maximum days"/><input type="number" value={policyForm.warningDays} onChange={e=>setPolicyForm({...policyForm,warningDays:e.target.value})} placeholder="Warning days"/><input type="datetime-local" value={policyForm.effectiveFrom} onChange={e=>setPolicyForm({...policyForm,effectiveFrom:e.target.value})}/><button className="setup-primary" disabled={busy} onClick={()=>void createPolicy()}>Create policy version</button></div>:null}</section>
      <section className="card"><div className="section-head"><div><div className="card-label">AGING QUEUE</div><h2>{aging.length} devices in view</h2></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All bands</option><option value="GREEN">On track</option><option value="ORANGE">Watch</option><option value="RED">Overdue</option><option value="PURPLE">Critical</option></select></div>
        <div className="table-wrap"><table><thead><tr><th>IMEI</th><th>Holder</th><th>Team</th><th>Region</th><th>Age</th><th>Status</th><th>Recovery</th><th></th></tr></thead><tbody>{aging.map((x:any)=><tr key={x.imeiId}><td><strong>{x.imei}</strong><div className="muted">{x.imei2??'No IMEI2'}</div></td><td>{x.holderName??'—'}</td><td>{x.teamName??'—'}</td><td>{x.regionName??'—'}</td><td>{x.totalFieldAgeDays}d{ x.daysOverdue>0?<div className="muted">{x.daysOverdue}d overdue</div>:<div className="muted">{x.daysRemaining}d left</div>}</td><td><span className={bandClass(x.agingStatus)}>{agingLabel(x.agingStatus)}</span></td><td>{statusLabel(String(x.recoveryStatus??''))}</td><td>{x.recoveryCaseId?<button className="setup-secondary" onClick={()=>void openCase(x.recoveryCaseId)}>Open case</button>:<span className="muted">Opened when overdue</span>}</td></tr>)}{!aging.length?<tr><td colSpan={8} className="muted">No aging issues were found in your area.</td></tr>:null}</tbody></table></div>
      </section>
      <section className="card"><div className="card-label">RECOVERY QUEUE</div><div className="table-wrap"><table><thead><tr><th>Case</th><th>IMEI</th><th>Holder</th><th>Officer</th><th>Status</th><th>Priority</th><th>Age</th><th></th></tr></thead><tbody>{cases.map((x:any)=><tr key={String(x.id)}><td>{x.caseNumber}</td><td>{x.imei}</td><td>{x.holderName??'—'}</td><td>{x.assignedOfficerName??'Unassigned'}</td><td>{statusLabel(String(x.status))}</td><td>{x.priority}</td><td>{x.totalFieldAgeDays??'—'}d</td><td><button className="setup-secondary" onClick={()=>void openCase(String(x.id))}>Open</button></td></tr>)}{!cases.length?<tr><td colSpan={8} className="muted">No open recovery cases in your area.</td></tr>:null}</tbody></table></div></section>
      {(me?.authorization.roles.includes('CEO')||me?.authorization.roles.includes('ADMIN'))?<section className="card"><div className="card-label">PAUSED ACCESS</div><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Source</th><th>Reason</th><th></th></tr></thead><tbody>{suspensions.map((x:any)=><tr key={String(x.id)}><td>{x.userName??x.userId}</td><td>{roleLabel(String(x.role??''))}</td><td>{statusLabel(String(x.suspensionSource??''))}</td><td>{x.reason}</td><td><button className="setup-secondary" disabled={busy} onClick={()=>void reinstate(String(x.userId))}>Reinstate</button></td></tr>)}{!suspensions.length?<tr><td colSpan={5} className="muted">No paused accounts need attention.</td></tr>:null}</tbody></table></div></section>:null}
      {selected?<section className="card"><div className="section-head"><div><div className="card-label">CASE DETAIL</div><h2>{String(selected.caseNumber)} · {statusLabel(String(selected.status))}</h2></div><button className="setup-secondary" onClick={()=>setSelected(null)}>Close detail</button></div><div className="scope-grid"><div><span>IMEI</span><strong>{String(selected.imei)}</strong></div><div><span>Holder</span><strong>{String(selected.holderName??'—')}</strong></div><div><span>Aging</span><strong>{agingLabel(String(selected.agingStatus??''))} / {String(selected.totalFieldAgeDays??'—')} days</strong></div></div><p className="setup-note">Use verified IMEI scanning for physical recovery. Recovery staff cannot change sales or skip the normal device transfer process.</p><div className="button-row"><button className="setup-primary" disabled={busy||String(selected.status)==='CLOSED'} onClick={()=>void actionActivity('CONTACTED')}>Record contact</button><button className="setup-secondary" disabled={busy||String(selected.status)==='CLOSED'} onClick={()=>void actionActivity('VISITED')}>Record visit</button><button className="setup-secondary" disabled={busy||String(selected.status)==='CLOSED'} onClick={()=>void actionActivity('PROMISE_TO_RETURN')}>Promise to return</button><button className="setup-secondary" disabled={busy||String(selected.status)==='CLOSED'} onClick={()=>void actionActivity('ESCALATED')}>Escalate</button><button className="setup-remove" disabled={busy||String(selected.status)!=='RECOVERED'} onClick={()=>void closeCase()}>Close recovered case</button></div><div className="card" style={{marginTop:16}}><div className="card-label">ACTIVITY HISTORY</div>{Array.isArray(selected.activities)&&selected.activities.length?selected.activities.map((a:any)=><div key={String(a.id)} className="setup-next"><strong>{activityLabel(String(a.activityType))}</strong><p>{a.result??'—'} · {a.notes??'—'}</p><small>{new Date(a.occurredAt).toLocaleString()}</small></div>):<p className="muted">No activity yet.</p>}</div></section>:null}
    </section></div></main>;
}
