-- Operator-run privilege template for the private Amaal intelligence service.
-- Run only from a privileged database administration session after choosing a strong secret.
-- This is intentionally NOT a normal application migration because managed Postgres role creation
-- policy varies and the password must never be committed to the repository.
--
-- Example operator sequence:
--   create role amaal_intelligence login password '<SET-IN-SECRET-MANAGER>';
--   grant usage on schema public to amaal_intelligence;
--   revoke all on all tables in schema public from amaal_intelligence;
--   grant select on public.read_model_sales_daily, public.read_model_product_daily,
--     public.read_model_commission_daily to amaal_intelligence;
--   grant select,insert,update on public.ml_model_artifacts,
--     public.ml_feature_validation_runs, public.ml_prediction_monitoring,
--     public.ml_monitoring_alerts, public.ml_canary_rollouts,
--     public.ml_prediction_outcomes, public.ml_governance_decisions,
--     public.ml_training_runs, public.ml_predictions, public.ml_prediction_evaluations
--     to amaal_intelligence;
--
-- Never grant INSERT/UPDATE/DELETE on authoritative business tables to this role.
-- After applying, validate with an explicit DENY test suite before supplying AMAAL_INTELLIGENCE_DATABASE_URL.
